language: node_js

node_js:
  - "8"

script:
  - yarn run test

cache:
  yarn: true
  directories:
    - node_modules

before_deploy:
  - yarn run build

branches:
  only:
    - master